### ISSUE TITLE
Error running environment-setup.ps1

### ISSUE THREAD

**Issue by pietrobr** [solliancenet/azure-synapse-analytics-ga-content-packs#2]
I have and error running the last step of the PS file,

$app = (az ad sp create-for-rbac -n "Azure Synapse Analytics GA Labs" --skip-assignment) | ConvertFrom-Json

$secretValue = ConvertTo-SecureString $app.password -AsPlainText -Force
Set-AzKeyVaultSecret -VaultName $keyVaultName -Name "ASA-GA-LABS" -SecretValue $secretValue

Looking into my Active Directory I see that an application with the same name already exists, so I think that also the this name must be unique with the prefix used for the setup.

For now I have created a new one by hand, not sure if it works correctly for the remaining part of the lab

**Comment by ciprianjichici** [comment]
The setup procedure was not designed to be run multiple times. The suggested approach is to delete the whole resource group every time you need to deploy the lab resources. In case you are dealing with intermediate failures, we confirm you need to check and address the naming issues individually for the conflicting resources.
