### ISSUE TITLE
Error running environment-setup.ps1 second

### ISSUE THREAD

**Issue by pietrobr** [solliancenet/azure-synapse-analytics-ga-content-packs#3]
When I run the script in my cloud shell , this line return empty password and so the sql scripts didn't run

$global:sqlPassword = $(Get-AzKeyVaultSecret -VaultName $keyVaultName -Name $keyVaultSQLUserSecretName).SecretValueText

I changed to make it work

$secret = Get-AzKeyVaultSecret -VaultName "asagakeyvaultpietrobr1" -Name "SQL-USER-ASA"
$ssPtr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secret.SecretValue)
try {
   $global:sqlPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($ssPtr)
} finally {
   [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ssPtr)
}

**Comment by ciprianjichici** [comment]
The SecretValueText property has been deprecated.

As per the latest version of the documentation available at https://docs.microsoft.com/en-us/powershell/module/az.keyvault/get-azkeyvaultsecret?view=azps-5.3.0&viewFallbackFrom=azps-5.0.0#example-5--get-the-plain-text-value-of-the-current-version-of-a-specific-secret, the recommended way to go is:

```powershell
$secretText = Get-AzKeyVaultSecret -VaultName 'Contoso' -Name 'ITSecret' -AsPlainText
```

We have updated the setup script accordingly in the repo.
