### ISSUE TITLE
Issue with running .\environment-setup.ps1

### ISSUE THREAD

**Issue by mamjadi** [solliancenet/azure-synapse-analytics-ga-content-packs#5]
When I run .\environment-setup.ps1 I get following errors:

Create SQL logins in master SQL pool
Invoke-Sqlcmd: /home/michael/asa/hands-on-labs/setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1099
Line |
1099 |  … atabase $sqlPoolName -Username $sqlUser -Password $global:sqlPassword
     |                                                      ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Create SQL users and role assignments in SQLPool01
Invoke-Sqlcmd: /home/michael/asa/hands-on-labs/setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1099
Line |
1099 |  … atabase $sqlPoolName -Username $sqlUser -Password $global:sqlPassword
     |                                                      ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Create schemas in SQLPool01
Invoke-Sqlcmd: /home/michael/asa/hands-on-labs/setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1099
Line |
1099 |  … atabase $sqlPoolName -Username $sqlUser -Password $global:sqlPassword
     |                                                      ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Create tables in the [wwi] schema in SQLPool01
Invoke-Sqlcmd: /home/michael/asa/hands-on-labs/setup/solliance-synapse-automation/solliance-synapse-automation.psm1:1099
Line |
1099 |  … atabase $sqlPoolName -Username $sqlUser -Password $global:sqlPassword
     |                                                      ~~~~~~~~~~~~~~~~~~~
     | Cannot validate argument on parameter 'Password'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
........................................................................................................................................

Also at the end I get:
Preparing environment for labs
ConvertTo-SecureString: /home/michael/asa/hands-on-labs/setup/automation/environment-setup.ps1:424
Line |
 424 |  $secretValue = ConvertTo-SecureString $app.password -AsPlainText -For …
     |                                        ~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'String' because it is null.

Set-AzKeyVaultSecret: /home/michael/asa/hands-on-labs/setup/automation/environment-setup.ps1:425
Line |
 425 |  … VaultName $keyVaultName -Name "ASA-GA-LABS" -SecretValue $secretValue
     |                                                             ~~~~~~~~~~~~
     | Cannot bind argument to parameter 'SecretValue' because it is null.

PS /home/michael/asa/hands-on-labs/setup/automation>
_

**Comment by lipinght** [comment]
got the exact same error, and "Azure Synapse Analytics GA Labs" is not showing in AAD's app registration.

**Comment by ciprianjichici** [comment]
The root cause of the sequence of errors is a missing SQL admin password.

You need to provide a non-empty SQL admin password when configuring the template during deployment. Please check https://github.com/solliancenet/azure-synapse-analytics-ga-content-packs/blob/main/hands-on-labs/setup/asa-workspace-deploy.md for detailed instructions.
